#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
touch ".databases.ini"
cat >".pgbouncer.ini" <<EOF
[pgbouncer]
admin_users = postgres
application_name_add_host = 1
auth_hba_file = pg_data/pg_hba.conf
auth_type = hba
auth_user = postgres
listen_addr = *
listen_port = 5433
log_stats = 0
stats_users = postgres
unix_socket_dir = /run/postgresql
unix_socket_group = postgres
unix_socket_mode = 0777
EOF
if [ -n "$SERVER_CERT" ]; then echo "client_tls_cert_file = $SERVER_CERT" >>".pgbouncer.ini"; fi
if [ -n "$SERVER_KEY" ]; then echo "client_tls_key_file = $SERVER_KEY" >>".pgbouncer.ini"; fi
if [ -n "$SSL_CA_FILE" ]; then echo "client_tls_ca_file = $SSL_CA_FILE" >>".pgbouncer.ini"; fi
if [ -n "$SSL_MODE" ]; then echo "client_tls_sslmode = $SSL_MODE" >>".pgbouncer.ini"; fi
if [ -n "$PG_AUTOCTL_SERVER_CERT" ]; then echo "client_tls_cert_file = $PG_AUTOCTL_SERVER_CERT" >>".pgbouncer.ini"; fi
if [ -n "$PG_AUTOCTL_SERVER_KEY" ]; then echo "client_tls_key_file = $PG_AUTOCTL_SERVER_KEY" >>".pgbouncer.ini"; fi
if [ -n "$PG_AUTOCTL_SSL_CA_FILE" ]; then echo "client_tls_ca_file = $PG_AUTOCTL_SSL_CA_FILE" >>".pgbouncer.ini"; fi
if [ -n "$PG_AUTOCTL_SSL_MODE" ]; then echo "client_tls_sslmode = $PG_AUTOCTL_SSL_MODE" >>".pgbouncer.ini"; fi
cat >>".pgbouncer.ini" <<EOF

[databases]
%include .databases.ini
EOF
