#!/bin/sh -eux

touch .databases.ini
cat >.pgbouncer.ini <<EOF
[pgbouncer]
admin_users = postgres
application_name_add_host = 1
auth_hba_file = data/pg_hba.conf
auth_type = hba
auth_user = postgres
listen_addr = *
listen_port = 5433
log_stats = 0
stats_users = postgres
unix_socket_dir = /run/postgresql
unix_socket_group = postgres
unix_socket_mode = 0777

[databases]
%include .databases.ini
EOF
