#!/bin/sh -eux

realpath "$0"
cd "$(dirname "$0")"
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
cd "$HOME"
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql /var/log/pgbouncer
test -f /run/postgresql/postgres.run
chpst -u "$USER":"$GROUP" pg_isready
chpst -u "$USER":"$GROUP" pg_ctl status
test -f ".pgbouncer.ini" || chpst -u "$USER":"$GROUP" /etc/service/pgbouncer/init
chpst -u "$USER":"$GROUP" /etc/service/pgbouncer/data
test -f .pgbouncer.ini
test -f .databases.ini
exec chpst -u "$USER":"$GROUP" pgbouncer .pgbouncer.ini
