#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
chpst -u "$USER":"$GROUP" /etc/service/repmgr/hba
chpst -u "$USER":"$GROUP" cat >>"$PGDATA/postgresql.conf" <<EOF

hot_standby = on
max_replication_slots = 10
max_wal_senders = 10
shared_preload_libraries = 'pg_backtrace,pg_task,repmgr,pg_partman_bgw,pg_stat_statements'
wal_log_hints = on
EOF
