#!/bin/sh

exec 2>&1
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql /var/log/pgbouncer
rm -f /run/postgresql/pgbouncer.run
test -f /run/postgresql/postgres.run || exit $?
realpath "$0"
set -ex
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
chpst -u "$USER":"$GROUP" pg_ctl status
test -f "$HOME/pgbouncer.ini" || chpst -u "$USER":"$GROUP" /etc/multi/pgbouncer/conf
exec chpst -u "$USER":"$GROUP" -L /run/postgresql/pgbouncer.run pgbouncer "$HOME/pgbouncer.ini"
