#!/bin/sh -eux

realpath "$0"
DT="$(date "+%F %T")"
echo "all dump begin at $DT"
FILE="$(psql -Aqt -c 'SELECT pg_walfile_name(pg_current_wal_lsn())')"
pg_archivecleanup -x .gz pg_arclog "$FILE"
DUMP="pg_dump/$DT"
mkdir -p "$DUMP"
cd "$DUMP"
pg_dumpall --clean --if-exists --globals-only --file=globals.sql --quote-all-identifiers
psql postgres -qtAc "select datname from pg_database" | grep -v template | grep -v postgres | while read -r NAME; do
    echo "$NAME dump begin at $(date "+%F %T")"
    pg_dump --jobs=$(nproc) --blobs --disable-triggers --clean --if-exists --create --format=directory --compress=9 --file="$NAME" --quote-all-identifiers --dbname="$NAME" --exclude-schema="_$NAME"
    echo "$NAME dump end at $(date "+%F %T")"
done
echo "all dump end at $(date "+%F %T")"
find pg_dump -mtime +35 -delete
