#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
case "$MODE" in
    "multi" )
        pg_rman backup --backup-mode=full --host="$(cat ~/gfs/primary)"
    ;;
    * )
        pg_rman backup --backup-mode=full
    ;;
esac
pg_rman validate
pg_rman purge
