#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cd "$(dirname "$0")"
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
cd "$HOME"
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql
test -f /run/postgresql/postgres.run
chpst -u "$USER":"$GROUP" pg_isready
chpst -u "$USER":"$GROUP" pg_ctl status
ln -fs "$PGDATA/smtpd.conf" /etc/smtpd/smtpd.conf
if [ -n "$PG_AUTOCTL" ]; then
    FORMATION="$(chpst -u "$USER":"$GROUP" pg_autoctl config get pg_autoctl.formation)"
    GROUPID="$(chpst -u "$USER":"$GROUP" pg_autoctl config get pg_autoctl.group)"
    NODEHOST="$(hostname)"
    NODENAME="$(chpst -u "$USER":"$GROUP" pg_autoctl config get pg_autoctl.name)"
    STATE="$(chpst -u "$USER":"$GROUP" pg_autoctl show state --group "$GROUPID" --formation "$FORMATION" --json | jq --unbuffered --raw-output ".[] | select(.nodename == \"$NODENAME\" and .nodehost == \"$NODEHOST\" and .current_group_state == .assigned_group_state) | .current_group_state")"
    if [ "$STATE" = "secondary" ]; then
        chpst -u "$USER":"$GROUP" sv stop smtp
    fi
fi
exec smtpd -d
