#!/bin/sh

exec 2>&1
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql
test -f /run/postgresql/postgres.run || exit $?
chpst -u "$USER":"$GROUP" pg_isready || exit $?
chpst -u "$USER":"$GROUP" pg_ctl status || exit $?
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
realpath "$0"
set -ex
exec smtpd -d
