#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cd "$(dirname "$0")"
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
cd "$HOME"
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql
test -f /run/postgresql/postgres.run
chpst -u "$USER":"$GROUP" pg_isready
chpst -u "$USER":"$GROUP" pg_ctl status
CONNINFO="$(pg_autoctl show uri --formation monitor)"
test -n "$CONNINFO"
if [ -n "$PG_AUTOCTL_MONITOR" ]; then
    FORMATION="$(pg_autoctl config get pg_autoctl.formation)"
    GROUPID="$(pg_autoctl config get pg_autoctl.group)"
    NODEHOST="$(hostname)"
    chpst -u "$USER":"$GROUP" pglisten --listen=state --conninfo="$CONNINFO" | jq --unbuffered --raw-output "select(.formation == \"$FORMATION\" and .groupId == $GROUPID and .health == \"good\" and ((.reportedState == \"primary\" and .goalState == \"primary\") or (.reportedState == \"wait_primary\" and .goalState == \"wait_primary\") or (.reportedState == \"single\" and .goalState == \"single\"))) | {host:.host, port:.port} | join(\" \")" | while read -r HOST PORT; do
        chpst -u "$USER":"$GROUP" echo "* = host=$HOST port=$PORT" >".databases.ini"
        chpst -u "$USER":"$GROUP" sv reload pgbouncer
        if [ "$HOST" = "$NODEHOST" ]; then
            chpst -u "$USER":"$GROUP" sv start smtp
        else
            chpst -u "$USER":"$GROUP" sv stop smtp
        fi
        chpst -u "$USER":"$GROUP" sv start primary || echo $?
    done
else
    chpst -u "$USER":"$GROUP" pglisten --listen=state --conninfo="$CONNINFO" | jq --unbuffered --raw-output "select((.reportedState == \"primary\" and .goalState == \"primary\") or (.reportedState == \"wait_primary\" and .goalState == \"wait_primary\") or (.reportedState == \"single\" and .goalState == \"single\")) | {host:.host, port:.port} | join(\" \")" | while read -r HOST PORT; do
        chpst -u "$USER":"$GROUP" /etc/service/cron/incremental
    done
fi
