#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cat >>"$PGDATA/postgresql.auto.conf" <<EOF
auto_explain.log_analyze = on
auto_explain.log_buffers = on
auto_explain.log_min_duration = 100
auto_explain.log_nested_statements = on
auto_explain.log_triggers = on
auto_explain.log_verbose = on
cluster_name = '$CLUSTER_NAME'
datestyle = 'iso, dmy'
idle_in_transaction_session_timeout = 1h
listen_addresses = '*'
log_line_prefix = '%m [%p] %r %u@%d/%a '
max_connections = 128
max_logical_replication_workers = 0
max_sync_workers_per_subscription = 0
max_wal_senders = 0
max_worker_processes = 128
plpgsql.extra_warnings = all
plpgsql.print_strict_params = on
track_activity_query_size = 102400
wal_level = minimal
EOF
if [ -n "$SERVER_CERT" ] && [ -n "$SERVER_KEY" ]; then echo "ssl = on" >>"$PGDATA/postgresql.auto.conf"; fi
if [ -n "$SERVER_CERT" ]; then echo "ssl_cert_file = '$SERVER_CERT'" >>"$PGDATA/postgresql.auto.conf"; fi
if [ -n "$SERVER_KEY" ]; then echo "ssl_key_file = '$SERVER_KEY'" >>"$PGDATA/postgresql.auto.conf"; fi
if [ -n "$SSL_CA_FILE" ]; then echo "ssl_ca_file = '$SSL_CA_FILE'" >>"$PGDATA/postgresql.auto.conf"; fi
if [ -n "$SSL_CRL_FILE" ]; then echo "ssl_crl_file = '$SSL_CRL_FILE'" >>"$PGDATA/postgresql.auto.conf"; fi
if [ -n "$PG_AUTOCTL" ] && [ -z "$PG_AUTOCTL_MONITOR" ]; then echo "shared_preload_libraries = 'pgautofailover,pg_stat_statements,auto_explain'" >>"$PGDATA/postgresql.auto.conf"
else echo "shared_preload_libraries = 'pg_task,pg_partman_bgw,pg_stat_statements,auto_explain'" >>"$PGDATA/postgresql.auto.conf"; fi
if [ "$(pgrep runsvdir | wc -l)" -gt "0" ]; then cat >>"$PGDATA/postgresql.auto.conf" <<EOF
archive_command = 'test ! -f "$HOME/pg_arclog/%f" && cp "%p" "$HOME/pg_arclog/%f" || echo "$HOME/pg_arclog/%f already exists!"'
archive_mode = on
log_directory = '$HOME/pg_log'
log_filename = 'postgresql-%Y-%m-%d.log'
logging_collector = on
log_truncate_on_rotation = on
max_wal_senders = 10
restore_command = 'test -f "$HOME/pg_arclog/%f" && cp "$HOME/pg_arclog/%f" "%p" || echo "$HOME/pg_arclog/%f does not exist!"'
wal_level = replica
EOF
fi
