#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
install -d -m 0750 -o "$USER" -g "$GROUP" "$PGDATA"
cd "$PGDATA" && chpst -u "$USER":"$GROUP" initdb
chpst -u "$USER":"$GROUP" /etc/service/postgres/conf
chpst -u "$USER":"$GROUP" /etc/service/postgres/hba
