#!/bin/sh

exec 2>&1
install -d -m 0750 -o "$USER" -g "$GROUP" "$HOME/pg_arclog" "$HOME/pg_log" "$HOME/pg_rman" "$PGDATA"
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql /var/log/postgresql
rm -f /run/postgresql/postgres.run
realpath "$0"
set -ex
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
rm -f "$PGDATA/postmaster.pid"
(cat /etc/hosts | grep "$(hostname)"; cat /etc/hosts.gfs | grep -v "$(hostname)") | sort -u >/etc/hosts.all
cat /etc/hosts.all >/etc/hosts.gfs
cat /etc/hosts.gfs >/etc/hosts
primary="$(test -f "$HOME/gfs/primary" && cat "$HOME/gfs/primary")"
test -n "$primary" || echo -n "$(hostname)" >"$HOME/gfs/primary"
primary="$(test -f "$HOME/gfs/primary" && cat "$HOME/gfs/primary")"
test -n "$primary"
chown "$USER":"$GROUP" "$HOME/gfs/primary"
if [ "$primary" != "$(hostname)" ]; then
    test -d "$PGDATA/base" || /etc/service/postgres/standby
    test -f "$PGDATA/standby.signal" || /etc/service/postgres/rejoin
else
    test -d "$PGDATA/base" || /etc/service/postgres/primary
fi
test -d "$PGDATA/base"
exec chpst -u "$USER":"$GROUP" -L /run/postgresql/postgres.run postmaster
