#!/bin/sh

exec 2>&1
install -d -m 0750 -o "$USER" -g "$GROUP" "$HOME/pg_arclog" "$HOME/pg_log" "$HOME/pg_rman" "$PGDATA"
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql /var/log/postgresql
realpath "$0"
set -ex
rm -f "$PGDATA/postmaster.pid"
test -d "$PGDATA/base" || /etc/service/postgres/init
test -d "$PGDATA/base"
exec chpst -u "$USER":"$GROUP" postmaster
