#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cat >"$BACKUP_PATH/pg_rman.ini" <<EOF
ARCLOG_PATH='$(echo -n "$HOME")/pg_arclog'
COMPRESS_DATA=true
KEEP_ARCLOG_DAYS=1
KEEP_DATA_DAYS=60
KEEP_DATA_GENERATIONS=9
KEEP_SRVLOG_DAYS=1
SRVLOG_PATH='$(echo -n "$HOME")/pg_log'
STANDBY_HOST=localhost
STANDBY_PORT=5432
WITH_SERVERLOG=true
EOF
