#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
pg_rman init
/etc/single/cron/conf
cat >"$HOME/crontab" <<EOF
0   0   *   *   1-6  /etc/single/cron/incremental
0   0   *   *   0,7  /etc/single/cron/full
EOF
