name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
  oracle:
    needs: latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: oracle
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: oracle
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  ubuntu:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  debian:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/debian
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: debian
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: debian
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  edge:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/edge
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: edge
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: edge
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  alpine14:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/alpine14
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: alpine-14
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: alpine-14
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  alpine13:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/alpine13
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: alpine-13
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: alpine-13
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  alpine12:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/alpine12
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: alpine-12
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: alpine-12
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  ubuntu14:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu14
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu-14
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu-14
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  ubuntu13:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu13
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu-13
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu-13
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  ubuntu12:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu12
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu-12
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu-12
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  ubuntu11:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu11
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu-11
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu-11
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  ubuntu10:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu10
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu-10
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu-10
        uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 10
  ubuntu9:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu9
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu-9
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu-9
        uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 10
