name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  oracle:
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: oracle
      INPUTS_TAG: oracle
    needs: latest
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-latest
    env:
      DOCKER_BUILD: false
      DOCKER_FROM: postgres.docker:latest
      GITHUB_TOKEN: ${{ github.token }}
    needs: latest
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
