name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  oracle:
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: oracle
      INPUTS_TAG: oracle
    needs: latest
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  edge:
    env:
      DOCKER_FROM: lib.docker:edge
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: edge
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-edge:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-edge
    env:
      DOCKER_BUILD: test
      DOCKER_FROM: postgres.docker:edge
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: test-edge
    needs: edge
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  REL_14_STABLE:
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: REL_14_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-REL_14_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-REL_14_STABLE
    env:
      DOCKER_BUILD: test
      DOCKER_FROM: postgres.docker:REL_14_STABLE
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: test-REL_14_STABLE
    needs: REL_14_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  REL_13_STABLE:
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: REL_13_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-REL_13_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-REL_13_STABLE
    env:
      DOCKER_BUILD: test
      DOCKER_FROM: postgres.docker:REL_13_STABLE
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: test-REL_13_STABLE
    needs: REL_13_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  REL_12_STABLE:
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: REL_12_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-REL_12_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-REL_12_STABLE
    env:
      DOCKER_BUILD: test
      DOCKER_FROM: postgres.docker:REL_12_STABLE
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: test-REL_12_STABLE
    needs: REL_12_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  debian:
    env:
      DOCKER_FROM: lib.docker:debian
      DOCKER_TYPE: apt
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: debian
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-debian:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-debian
    env:
      DOCKER_BUILD: test
      DOCKER_TYPE: apt
      DOCKER_FROM: postgres.docker:debian
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: test-debian
    needs: debian
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  ubuntu:
    env:
      DOCKER_FROM: lib.docker:ubuntu
      DOCKER_TYPE: apt
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test-ubuntu:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/test-ubuntu
    env:
      DOCKER_TYPE: apt
      DOCKER_BUILD: test
      DOCKER_FROM: postgres.docker:ubuntu
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: test-ubuntu
    needs: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
