name: Docker
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ github.token }}
  INPUTS_DOCKERFILE: ${{ github.job }}.Dockerfile
  INPUTS_TAG: ${{ github.job }}
concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}/${{ github.job }}
jobs:
  alpine:
    env:
      INPUTS_TAG: latest
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  alpine-test:
    needs: alpine
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  debian-test:
    needs: debian
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  gost:
    needs: alpine
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  ubuntu-test:
    needs: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  oracle:
    needs: gost
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  master-test:
    needs: master
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL_17_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL_17_STABLE-test:
    needs: REL_17_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL_16_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL_16_STABLE-test:
    needs: REL_16_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL_15_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL_15_STABLE-test:
    needs: REL_15_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL_14_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL_14_STABLE-test:
    needs: REL_14_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL_13_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL_13_STABLE-test:
    needs: REL_13_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL_12_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL_12_STABLE-test:
    needs: REL_12_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL_11_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL_11_STABLE-test:
    needs: REL_11_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL_10_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL_10_STABLE-test:
    needs: REL_10_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL9_6_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL9_6_STABLE-test:
    needs: REL9_6_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL9_5_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL9_5_STABLE-test:
    needs: REL9_5_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
  REL9_4_STABLE:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  REL9_4_STABLE-test:
    needs: REL9_4_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 30
