name: Docker
on:
  push:
    branches:
      - REL_13_STABLE
  repository_dispatch:
    types:
      - latest
      - REL_13_STABLE
  workflow_dispatch:
jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-action@v1
      - uses: rekgrpth/docker-login-build-push-action@v1
