name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  oracle:
    needs: latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: oracle
      INPUTS_TAG: oracle
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  edge:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/edge
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: edge
      INPUTS_TAG: edge
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  master:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/master
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: master
      INPUTS_TAG: master
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  debian:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/debian
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: debian
      INPUTS_TAG: debian
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  ubuntu:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: ubuntu
      INPUTS_TAG: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL_14_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL_14_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: REL_14_STABLE
      INPUTS_TAG: REL_14_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL_13_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL_13_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: REL_13_STABLE
      INPUTS_TAG: REL_13_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL_12_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL_12_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: REL_12_STABLE
      INPUTS_TAG: REL_12_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL_11_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL_11_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: REL_11_STABLE
      INPUTS_TAG: REL_11_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL_10_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL_10_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: REL_10_STABLE
      INPUTS_TAG: REL_10_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL9_6_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL9_6_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: REL9_6_STABLE
      INPUTS_TAG: REL9_6_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL9_5_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL9_5_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: REL9_5_STABLE
      INPUTS_TAG: REL9_5_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  REL9_4_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL9_4_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: REL9_4_STABLE
      INPUTS_TAG: REL9_4_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  test_REL_14_STABLE:
    needs: REL_14_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_REL_14_STABLE
      INPUTS_TAG: test_REL_14_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_REL_13_STABLE:
    needs: REL_13_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_REL_13_STABLE
      INPUTS_TAG: test_REL_13_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_REL_12_STABLE:
    needs: REL_12_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_REL_12_STABLE
      INPUTS_TAG: test_REL_12_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_REL_11_STABLE:
    needs: REL_11_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_REL_11_STABLE
      INPUTS_TAG: test_REL_11_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_REL_10_STABLE:
    needs: REL_10_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_REL_10_STABLE
      INPUTS_TAG: test_REL_10_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_REL9_6_STABLE:
    needs: REL9_6_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_REL9_6_STABLE
      INPUTS_TAG: test_REL9_6_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_REL9_5_STABLE:
    needs: REL9_5_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_REL9_5_STABLE
      INPUTS_TAG: test_REL9_5_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_REL9_4_STABLE:
    needs: REL9_4_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_REL9_4_STABLE
      INPUTS_TAG: test_REL9_4_STABLE
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_debian:
    needs: debian
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_debian
      INPUTS_TAG: test_debian
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
  test_ubuntu:
    needs: ubuntu
    env:
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_BRANCH: test_ubuntu
      INPUTS_TAG: test_ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
    timeout-minutes: 20
