name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
  REL_13_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL_13_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: REL_13_STABLE
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: REL_13_STABLE
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  REL_14_STABLE:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/REL_14_STABLE
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: REL_14_STABLE
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: REL_14_STABLE
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  ubuntu:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  debian:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/debian
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: debian
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: debian
        uses: rekgrpth/docker-login-build-push-shell-action@v1
