name: Docker
on:
  push:
    branches:
      - REL_13_STABLE
  repository_dispatch:
    types:
      - latest
      - REL_13_STABLE
  workflow_dispatch:
jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
  REL_14_STABLE:
    needs: build
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: REL_14_STABLE
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: REL_14_STABLE
        uses: rekgrpth/docker-login-build-push-shell-action@v1
